// Translations and locale-aware formatting shared by the web workspace and the field app.
// Add a language by adding a catalogue below and its code to LOCALES in api/routes/auth.js; missing keys fall back to
// English. German is a first draft and needs review by a native-speaking service professional before release.
export const LOCALES={en:'English',de:'Deutsch'};
const en={
  'app.tagline':'Plastics maintenance service workspace','app.field':'Engineer mobile workspace',
  'nav.dashboard':'Overview','nav.tickets':'Tickets','nav.equipment':'Equipment','nav.contracts':'Contracts','nav.parts':'Spare parts','nav.organisation':'Organisation','nav.providers':'Providers','nav.integrations':'IoT integration','nav.audit':'Audit trail','nav.account':'Account',
  'action.signIn':'Sign in','action.signOut':'Sign out','action.save':'Save','action.cancel':'Cancel','action.back':'Back','action.raiseTicket':'Raise ticket','action.assign':'Assign','action.updateStatus':'Update status','action.logWork':'Log work','action.checklist':'Checklist item','action.requestPart':'Request part','action.attach':'Attach photo / evidence','action.signoff':'Customer sign-off','action.done':'Done','action.undo':'Undo','action.approve':'Approve','action.reject':'Reject','action.quote':'Quote','action.viewQuotes':'View quotes','action.addVisit':'Add visit','action.extend':'Change renewal','action.edit':'Edit','action.deactivate':'Deactivate','action.activate':'Activate','action.syncNow':'Sync now','action.clear':'Clear',
  'label.email':'Email','label.password':'Password','label.language':'Language','label.priority':'Priority','label.status':'Status','label.asset':'Asset','label.opened':'Opened','label.assignment':'Assignment','label.unassigned':'Unassigned','label.symptoms':'Symptoms','label.errorCodes':'Error codes','label.impact':'Production impact','label.downtime':'Downtime','label.minutes':'minutes','label.note':'Note','label.signerName':'Signer name','label.signature':'Signature','label.responseDue':'Response due','label.coverage':'Contract coverage','label.notCovered':'Not covered by an active contract','label.exclusions':'Exclusions','label.commitments':'Commitments','label.renews':'Renews','label.starts':'Starts','label.visits':'Visits','label.responseTarget':'Response target','label.hours':'h','label.days':'days','label.reference':'Reference',
  'dash.open':'Open tickets','dash.unassigned':'Awaiting assignment','dash.escalated':'Escalated','dash.breaches':'Response targets missed','dash.meanResponse':'Mean response','dash.downtime':'Downtime','dash.repeat':'Repeat-fault assets','dash.alarms':'Active machine alarms','dash.activeWork':'Active work','dash.responseByPriority':'Mean response by priority','dash.repeatFaults':'Repeat faults (90 days)','dash.downtimeByAsset':'Downtime by asset','dash.upcoming':'Upcoming maintenance','dash.overdue':'Overdue visits','dash.renewals':'Renewals in the next 90 days','dash.renewalsDue':'Renewals due (90 days)','dash.reporting':'Assets reporting','dash.staleData':'Stale or no data','dash.noDevice':'No IoT device','dash.none':'None',
  'section.checklist':'Service checklist','section.work':'Work and parts used','section.evidence':'Evidence and sign-off','section.activity':'Activity','section.machineData':'Machine data','section.assigned':'Assigned work',
  'msg.saved':'Saved','msg.savedOffline':'Saved on this device. It will sync when connected.','msg.awaitingSignoff':'Awaiting customer sign-off','msg.signedBy':'Signed by {name} on {date}','msg.signedOnSite':'on site, collected by the engineer','msg.noRecords':'No records yet','msg.noteRequired':'A note is required to decline or escalate.','msg.signFirst':'Ask the customer to sign in the box first.','msg.declined':'Ticket declined and returned to dispatch.','msg.breached':'Response target missed','msg.onTrack':'On track',
  'status.open':'Open','status.assigned':'Assigned','status.accepted':'Accepted','status.in_progress':'In progress','status.escalated':'Escalated','status.completed':'Completed','status.declined':'Declined','status.signed_off':'Signed off',
  'status.requested':'Requested','status.quoted':'Quoted','status.approved':'Approved','status.rejected':'Rejected','status.ordered':'Ordered','status.shipped':'Shipped','status.fulfilled':'Fulfilled','status.pending':'Pending','status.superseded':'Superseded',
  'status.scheduled':'Scheduled','status.cancelled':'Cancelled','status.active':'Active','status.expired':'Expired',
  'status.current':'Current','status.stale':'Stale','status.missing':'Missing','status.unmapped':'Not connected','status.inactive':'Inactive','status.succeeded':'Succeeded','status.failed':'Failed','status.running':'Running',
  'priority.low':'Low','priority.medium':'Medium','priority.high':'High','priority.critical':'Critical',
  'severity.info':'Info','severity.warning':'Warning','severity.critical':'Critical',
  'machine.injection':'Injection moulding','machine.blow':'Blow moulding','machine.extrusion':'Extrusion','machine.mould':'Mould','machine.auxiliary':'Auxiliary',
  'role.platform_admin':'Platform admin','role.dispatcher':'Dispatcher','role.engineer':'Service engineer','role.customer_admin':'Customer admin','role.plant_manager':'Plant manager','role.maintenance':'Maintenance','role.provider_admin':'Provider admin','role.provider_engineer':'Provider engineer'
};
const de={
  'app.tagline':'Service-Arbeitsplatz für die Kunststoffverarbeitung','app.field':'Mobiler Arbeitsplatz für Techniker',
  'nav.dashboard':'Übersicht','nav.tickets':'Störmeldungen','nav.equipment':'Anlagen','nav.contracts':'Wartungsverträge','nav.parts':'Ersatzteile','nav.organisation':'Organisation','nav.providers':'Servicepartner','nav.integrations':'IoT-Anbindung','nav.audit':'Prüfprotokoll','nav.account':'Konto',
  'action.signIn':'Anmelden','action.signOut':'Abmelden','action.save':'Speichern','action.cancel':'Abbrechen','action.back':'Zurück','action.raiseTicket':'Störung melden','action.assign':'Zuweisen','action.updateStatus':'Status ändern','action.logWork':'Arbeit erfassen','action.checklist':'Prüfpunkt','action.requestPart':'Ersatzteil anfordern','action.attach':'Foto / Nachweis anhängen','action.signoff':'Kundenabnahme','action.done':'Erledigt','action.undo':'Zurücksetzen','action.approve':'Freigeben','action.reject':'Ablehnen','action.quote':'Angebot','action.viewQuotes':'Angebote','action.addVisit':'Termin hinzufügen','action.extend':'Verlängerung ändern','action.edit':'Bearbeiten','action.deactivate':'Deaktivieren','action.activate':'Aktivieren','action.syncNow':'Jetzt synchronisieren','action.clear':'Löschen',
  'label.email':'E-Mail','label.password':'Passwort','label.language':'Sprache','label.priority':'Priorität','label.status':'Status','label.asset':'Anlage','label.opened':'Gemeldet','label.assignment':'Zuständig','label.unassigned':'Nicht zugewiesen','label.symptoms':'Symptome','label.errorCodes':'Fehlercodes','label.impact':'Auswirkung auf die Produktion','label.downtime':'Stillstand','label.minutes':'Minuten','label.note':'Notiz','label.signerName':'Name des Unterzeichners','label.signature':'Unterschrift','label.responseDue':'Reaktion fällig','label.coverage':'Vertragsdeckung','label.notCovered':'Nicht durch einen aktiven Vertrag abgedeckt','label.exclusions':'Ausschlüsse','label.commitments':'Leistungen','label.renews':'Verlängerung','label.starts':'Beginn','label.visits':'Termine','label.responseTarget':'Reaktionszeit','label.hours':'Std.','label.days':'Tage','label.reference':'Referenz',
  'dash.open':'Offene Störmeldungen','dash.unassigned':'Warten auf Zuweisung','dash.escalated':'Eskaliert','dash.breaches':'Reaktionszeit überschritten','dash.meanResponse':'Mittlere Reaktionszeit','dash.downtime':'Stillstand','dash.repeat':'Anlagen mit Wiederholfehlern','dash.alarms':'Aktive Maschinenalarme','dash.activeWork':'Laufende Arbeiten','dash.responseByPriority':'Mittlere Reaktionszeit nach Priorität','dash.repeatFaults':'Wiederholfehler (90 Tage)','dash.downtimeByAsset':'Stillstand nach Anlage','dash.upcoming':'Anstehende Wartung','dash.overdue':'Überfällige Termine','dash.renewals':'Verlängerungen in den nächsten 90 Tagen','dash.renewalsDue':'Verlängerungen fällig (90 Tage)','dash.reporting':'Anlagen mit aktuellen Daten','dash.staleData':'Veraltete oder keine Daten','dash.noDevice':'Ohne IoT-Gerät','dash.none':'Keine',
  'section.checklist':'Service-Checkliste','section.work':'Arbeiten und verbaute Teile','section.evidence':'Nachweise und Abnahme','section.activity':'Verlauf','section.machineData':'Maschinendaten','section.assigned':'Zugewiesene Aufträge',
  'msg.saved':'Gespeichert','msg.savedOffline':'Auf dem Gerät gespeichert. Wird bei Verbindung synchronisiert.','msg.awaitingSignoff':'Kundenabnahme ausstehend','msg.signedBy':'Abgenommen von {name} am {date}','msg.signedOnSite':'vor Ort, erfasst durch den Techniker','msg.noRecords':'Noch keine Einträge','msg.noteRequired':'Zum Ablehnen oder Eskalieren ist eine Notiz erforderlich.','msg.signFirst':'Bitte zuerst den Kunden im Feld unterschreiben lassen.','msg.declined':'Auftrag abgelehnt und an die Disposition zurückgegeben.','msg.breached':'Reaktionszeit überschritten','msg.onTrack':'Im Plan',
  'status.open':'Offen','status.assigned':'Zugewiesen','status.accepted':'Angenommen','status.in_progress':'In Arbeit','status.escalated':'Eskaliert','status.completed':'Abgeschlossen','status.declined':'Abgelehnt','status.signed_off':'Abgenommen',
  'status.requested':'Angefordert','status.quoted':'Angeboten','status.approved':'Freigegeben','status.rejected':'Abgelehnt','status.ordered':'Bestellt','status.shipped':'Versandt','status.fulfilled':'Geliefert','status.pending':'Offen','status.superseded':'Ersetzt',
  'status.scheduled':'Geplant','status.cancelled':'Storniert','status.active':'Aktiv','status.expired':'Abgelaufen',
  'status.current':'Aktuell','status.stale':'Veraltet','status.missing':'Fehlt','status.unmapped':'Nicht angebunden','status.inactive':'Inaktiv','status.succeeded':'Erfolgreich','status.failed':'Fehlgeschlagen','status.running':'Läuft',
  'priority.low':'Niedrig','priority.medium':'Mittel','priority.high':'Hoch','priority.critical':'Kritisch',
  'severity.info':'Info','severity.warning':'Warnung','severity.critical':'Kritisch',
  'machine.injection':'Spritzgießen','machine.blow':'Blasformen','machine.extrusion':'Extrusion','machine.mould':'Werkzeug','machine.auxiliary':'Peripherie',
  'role.platform_admin':'Plattform-Admin','role.dispatcher':'Disposition','role.engineer':'Servicetechniker','role.customer_admin':'Kunden-Admin','role.plant_manager':'Werksleitung','role.maintenance':'Instandhaltung','role.provider_admin':'Partner-Admin','role.provider_engineer':'Partner-Techniker'
};
const catalogues={en,de};
let current='en';
export function setLocale(code) { current=catalogues[code]?code:'en'; document.documentElement.lang=current; }
export const locale=()=>current;
export function t(key,vars) { const s=catalogues[current][key]??en[key]??key; return vars?s.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??''):s; }
// Enum values from the API (statuses, priorities, roles, machine types); unknown values are shown humanised.
export const label=(group,value)=>value==null?'':(catalogues[current][`${group}.${value}`]??en[`${group}.${value}`]??String(value).replaceAll('_',' '));

const zoneOk=zone=>{ try { new Intl.DateTimeFormat('en',{timeZone:zone}); return true; } catch { return false; } };
// Times are shown in the zone where the work happens (the plant's), with the zone name, so a dispatcher in one
// country and an engineer in another read the same wall-clock time.
export function formatDateTime(iso,zone) {
  if (!iso) return '—';
  const timeZone=zone&&zoneOk(zone)?zone:undefined;
  return new Intl.DateTimeFormat(current,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone,timeZoneName:'short'}).format(new Date(iso));
}
export function formatDate(iso,zone) { if (!iso) return '—'; return new Intl.DateTimeFormat(current,{year:'numeric',month:'short',day:'numeric',timeZone:zone&&zoneOk(zone)?zone:'UTC'}).format(new Date(iso)); }
export const formatNumber=(n,digits=0)=>n==null?'—':new Intl.NumberFormat(current,{maximumFractionDigits:digits}).format(n);
const fractionDigits=code=>new Intl.NumberFormat('en',{style:'currency',currency:code}).resolvedOptions().maximumFractionDigits;
export const formatMoney=(minor,code)=>minor==null?'—':new Intl.NumberFormat(current,{style:'currency',currency:code}).format(minor/10**fractionDigits(code));
export const toMinorUnits=(major,code)=>Math.round(Number(major)*10**fractionDigits(code));
export const formatTemperature=(c,units)=>c==null?'—':units==='imperial'?`${formatNumber(c*9/5+32,1)} °F`:`${formatNumber(c,1)} °C`;
export function formatDuration(minutes) { if (minutes==null) return '—'; return minutes<120?`${formatNumber(minutes)} min`:minutes<2880?`${formatNumber(minutes/60,1)} ${t('label.hours')}`:`${formatNumber(minutes/1440,1)} ${t('label.days')}`; }
