import { qrSvg } from './qr.js';

const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={token:null,user:null,page:'dashboard',detail:null,notice:'',error:'',data:{}};
const names={dashboard:'Overview',tickets:'Tickets',equipment:'Equipment',contracts:'Contracts',parts:'Spare parts',organisation:'Organisation',providers:'Providers',audit:'Audit trail'};
const customer=()=>['customer_admin','plant_manager','maintenance'].includes(state.user.role), internal=()=>['platform_admin','dispatcher','engineer'].includes(state.user.role), manager=()=>['platform_admin','customer_admin'].includes(state.user.role);
const btn=(label,action,cls='')=>`<button class="${cls}" data-action="${action}">${esc(label)}</button>`;
const pill=s=>`<span class="pill ${esc(s)}">${esc(s?.replaceAll('_',' '))}</span>`;
const date=s=>s?new Date(s).toLocaleString(): '—';
const api=async(path,method='GET',body)=>{const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json',...(state.token?{authorization:`Bearer ${state.token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;};
function message(text,isError=false){state.notice=isError?'':text;state.error=isError?text:'';render();}
async function load(){const paths=['dashboard','companies','plants','equipment','tickets','contracts','parts','providers','users','audit'];const out=await Promise.all(paths.map(async p=>[p,await api('/'+p).catch(()=>[])]));state.data=Object.fromEntries(out);render();}
function login(){ $('#app').innerHTML=`<div class="login"><div class="brand" style="color:#12323d">Mould<span>Care</span></div><h1>Service operations</h1><p class="muted">Sign in to the local demo.</p><form id="login"><label>Email</label><input name="email" type="email" required value="acme@demo.test"><label>Password</label><input name="password" type="password" required value="DemoPass123!"><button>Sign in</button></form><p class="muted">Try admin@demo.test, dispatch@demo.test, engineer@demo.test, acme@demo.test, nova@demo.test, atlas@demo.test, or euro@demo.test. All use DemoPass123!</p>${state.error?`<p class="notice error">${esc(state.error)}</p>`:''}</div>`;$('#login').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),r=await api('/auth/login','POST',Object.fromEntries(f));state.token=r.token;state.user=r.user;state.error='';await load();}catch(err){message(err.message,true)}};}
function layout(content){const nav=['dashboard','tickets','equipment','contracts','parts','organisation','providers','audit'].filter(p=>p==='organisation'?manager()||state.user.role==='provider_admin':p==='providers'?internal()||state.user.role.startsWith('provider_'):p==='audit'?manager():true);$('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand">Mould<span>Care</span></div>${nav.map(p=>`<button class="nav ${state.page===p?'active':''}" data-nav="${p}">${names[p]}</button>`).join('')}<div class="profile"><b>${esc(state.user.name)}</b><br>${esc(state.user.role.replaceAll('_',' '))}<br><a class="click" data-action="logout">Sign out</a></div></aside><main class="main"><div class="top"><div><h1>${names[state.page]}</h1><div class="muted">Plastics maintenance service workspace</div></div><div class="muted">${new Date().toLocaleDateString()}</div></div>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}${content}</main></div>`;document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>{state.page=el.dataset.nav;state.detail=null;state.error='';state.notice='';render()});document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action,el.dataset.id));}
function render(){if(!state.user)return login();let content='';if(state.detail?.type==='ticket')content=ticketDetail();else if(state.detail?.type==='equipment')content=assetDetail();else content=({dashboard:overview,tickets:tickets,equipment:equipment,contracts:contracts,parts:parts,organisation:organisation,providers:providers,audit:auditView}[state.page]||overview)();layout(content);document.querySelectorAll('form[data-form]').forEach(el=>el.onsubmit=submit);}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">No records yet</td></tr>`}</tbody></table></div>`;}
function overview(){const d=state.data.dashboard||{},up=d.upcomingMaintenance||[];return `<div class="grid"><div class="card"><small>Open tickets</small><strong>${d.openTickets??0}</strong></div><div class="card"><small>Mean response</small><strong>${d.averageResponseMinutes==null?'—':d.averageResponseMinutes+'m'}</strong></div><div class="card"><small>Downtime</small><strong>${Math.round((d.downtimeMinutes||0)/60)}h</strong></div><div class="card"><small>Repeat fault assets</small><strong>${d.repeatFaultAssets||0}</strong></div></div><div class="detail"><div class="panel"><h2>Active work</h2>${table(['Ticket','Priority','Status','Impact'],(d.tickets||[]).map(t=>`<tr><td><a data-action="ticket" data-id="${t.id}">${esc(t.title)}</a></td><td>${pill(t.priority)}</td><td>${pill(t.status)}</td><td>${esc(t.production_impact)}</td></tr>`))}</div><div class="panel"><h2>Priority mix</h2>${Object.entries(d.byPriority||{}).map(([p,n])=>`<div class="spread"><span>${esc(p)}</span><b>${n}</b></div><div class="bar"><span style="width:${d.openTickets?Math.round(n/d.openTickets*100):0}%"></span></div><br>`).join('')}<h2>Upcoming maintenance</h2>${up.length?up.map(v=>`<p class="mini">${esc(v.make)} ${esc(v.model)}<br>${date(v.due_at)}</p>`).join(''):'<p class="muted">No scheduled visits</p>'}</div></div>`;}
function tickets(){const list=state.data.tickets||[],assets=state.data.equipment||[];return `<div class="panel spread"><div><h2>Breakdown queue</h2><span class="muted">${list.length} visible tickets</span></div>${customer()||internal()?btn('Raise ticket','newTicket'):''}</div><div class="panel">${table(['Ticket','Asset','Priority','Status','Opened','Assignment'],list.map(t=>`<tr><td><a data-action="ticket" data-id="${t.id}">${esc(t.title)}</a><div class="muted">${esc(t.error_codes)}</div></td><td>${esc(assets.find(e=>e.id===t.equipment_id)?.model||t.equipment_id)}</td><td>${pill(t.priority)}</td><td>${pill(t.status)}</td><td>${date(t.created_at)}</td><td>${esc(t.assigned_provider_id||t.assigned_user_id||'Unassigned')}</td></tr>`))}</div><div id="form-slot"></div>`;}
function equipment(){const list=state.data.equipment||[];return `<div class="panel spread"><div><h2>Asset register</h2><span class="muted">Machines, moulds and auxiliary assets</span></div>${manager()?btn('Add equipment','newEquipment'):''}</div><div class="panel">${table(['Asset','Machine type','Serial','Location','Plant'],list.map(e=>`<tr><td><a data-action="equipment" data-id="${e.id}">${esc(e.make)} ${esc(e.model)}</a></td><td>${pill(e.machine_type)}</td><td>${esc(e.serial_number)}</td><td>${esc(e.location)}</td><td>${esc((state.data.plants||[]).find(p=>p.id===e.plant_id)?.name||'')}</td></tr>`))}</div><div id="form-slot"></div>`;}
function contracts(){const list=state.data.contracts||[];return `<div class="panel spread"><h2>Annual maintenance contracts</h2>${manager()||state.user.role==='dispatcher'?btn('New contract','newContract'):''}</div>${list.map(c=>`<div class="panel"><div class="spread"><h2>${esc(c.title)}</h2>${pill(c.status)}</div><div class="grid"><div><small>Starts</small><p>${date(c.starts_at)}</p></div><div><small>Renews</small><p>${date(c.renews_at)}</p></div><div><small>Covered assets</small><p>${c.equipmentIds.length}</p></div><div><small>Visits</small><p>${c.visits.length}</p></div></div><p><b>Commitments:</b> ${esc(c.commitments)}</p><p><b>Exclusions:</b> ${esc(c.exclusions)}</p>${c.visits.map(v=>`<div class="mini">${date(v.due_at)} · ${esc(v.notes)} · ${pill(v.status)} ${v.status==='scheduled'&&(manager()||state.user.role==='dispatcher')?btn('Complete visit','visitDone:'+v.id,'secondary'):''}</div>`).join('')}</div>`).join('')||'<div class="panel empty">No contracts</div>'}<div id="form-slot"></div>`;}
function parts(){const list=state.data.parts||[];return `<div class="panel"><h2>Spare parts requests</h2>${table(['Part','Quantity','Status','Created','Action'],list.map(p=>`<tr><td>${esc(p.item)}</td><td>${p.quantity}</td><td>${pill(p.status)}</td><td>${date(p.created_at)}</td><td>${btn('View quotes','quotes:'+p.id,'secondary')}${internal()&&p.status==='requested'?btn('Quote','quote:'+p.id):''}${internal()&&p.status==='approved'?btn('Mark fulfilled','fulfil:'+p.id):''}</td></tr>`))}</div><div id="form-slot"></div>`;}
function organisation(){const companies=state.data.companies||[],plants=state.data.plants||[],users=state.data.users||[];return `<div class="section-actions">${state.user.role==='platform_admin'?btn('Add company','newCompany'):''}${manager()?btn('Add plant','newPlant'):''}${manager()||state.user.role==='provider_admin'?btn('Add user','newUser'):''}</div><div class="panel"><h2>Companies</h2>${table(['Name','Timezone','Currency'],companies.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.timezone)}</td><td>${esc(c.currency)}</td></tr>`))}</div><div class="panel"><h2>Plants</h2>${table(['Name','Country','Service area','Timezone'],plants.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.country)}</td><td>${esc(p.service_area)}</td><td>${esc(p.timezone)}</td></tr>`))}</div><div class="panel"><h2>Users</h2>${table(['Name','Email','Role'],users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${pill(u.role)}</td></tr>`))}</div><div id="form-slot"></div>`;}
function providers(){const list=state.data.providers||[];return `<div class="panel spread"><h2>Service partners</h2>${state.user.role==='platform_admin'?btn('Add provider','newProvider'):''}</div><div class="panel">${table(['Provider','Approved','Areas','Skills','Action'],list.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.approved?'Yes':'No'}</td><td>${esc(p.service_areas)}</td><td>${esc(p.skills)}</td><td>${state.user.role==='platform_admin'?btn(p.approved?'Suspend':'Approve','approve:'+p.id):''}</td></tr>`))}</div><div id="form-slot"></div>`;}
function auditView(){return `<div class="panel"><h2>Recent audit events</h2>${table(['Time','Action','Entity','Actor'],(state.data.audit||[]).map(a=>`<tr><td>${date(a.created_at)}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type)} ${esc(a.entity_id)}</td><td>${esc(a.actor_id)}</td></tr>`))}</div>`;}
function ticketDetail(){const t=state.detail.value,asset=t.asset||((state.data.equipment||[]).find(e=>e.id===t.equipment_id));const canWork=internal()||state.user.role.startsWith('provider_');return `<div class="section-actions">${btn('← Tickets','back','secondary')}${canWork&&['assigned','accepted','in_progress','escalated'].includes(t.status)?btn('Update status','status'):''}${canWork?btn('Add work log','workLog')+btn('Checklist item','checklist'):''}${customer()||canWork?btn('Request part','part'):''}${customer()&&t.status==='completed'&&!t.signoff?btn('Customer sign-off','signoff'):''}${internal()&&t.status!=='completed'?btn('Assign','assign'):''}${btn('Attach photo / evidence','attachment')}</div><div class="detail"><div><div class="panel"><div class="spread"><h2>${esc(t.title)}</h2>${pill(t.status)}</div><p>${pill(t.priority)} · ${esc(asset?.make||'')} ${esc(asset?.model||'')} · ${esc(t.plant?.name||'')}</p><p><b>Symptoms:</b> ${esc(t.symptoms)}</p><p><b>Error codes:</b> ${esc(t.error_codes||'—')}</p><p><b>Production impact:</b> ${esc(t.production_impact)}</p><p><b>Downtime:</b> ${t.downtime_minutes} minutes</p></div><div class="panel"><h2>Service checklist</h2>${t.checklist.length?t.checklist.map(c=>`<p>${c.done?'☑':'☐'} ${esc(c.item)} <span class="muted">${esc(c.note)}</span> ${canWork&&!c.done?btn('Done','done:'+c.id,'secondary'):''}</p>`).join(''):'<p class="muted">No checklist entries yet.</p>'}</div><div class="panel"><h2>Work and parts used</h2>${t.workLogs.length?t.workLogs.map(w=>`<p>${esc(w.description)} <span class="muted">${w.minutes} min · ${esc(w.parts_used)}</span></p>`).join(''):'<p class="muted">No work logged yet.</p>'}</div><div class="panel"><h2>Evidence and sign-off</h2>${t.attachments.map(a=>`<p><a href="/api/attachments/${a.id}" data-download="${a.id}">${esc(a.filename)}</a> · ${esc(a.kind)}</p>`).join('')||'<p class="muted">No attachments.</p>'}<p>${t.signoff?`Signed by ${esc(t.signoff.signer_name)} on ${date(t.signoff.signed_at)}`:'Awaiting customer sign-off'}</p></div></div><div><div class="panel"><h2>Activity</h2>${t.events.map(e=>`<p class="mini"><b>${esc(e.event_type.replaceAll('_',' '))}</b> · ${esc(e.actor_name)}<br>${date(e.created_at)}<br>${esc(e.detail)}</p>`).join('')}</div></div></div><div id="form-slot"></div>`;}
function assetDetail(){const e=state.detail.value;return `<div class="section-actions">${btn('← Equipment','back','secondary')}${manager()?btn('Attach manual or photo','attachment'):''}</div><div class="detail"><div class="panel"><h2>${esc(e.make)} ${esc(e.model)}</h2><p>${pill(e.machine_type)} · Serial ${esc(e.serial_number)}</p><p>Location: ${esc(e.location)}</p><h2>Manuals and photos</h2>${e.attachments.map(a=>`<p><a href="/api/attachments/${a.id}" data-download="${a.id}">${esc(a.filename)}</a> · ${esc(a.kind)}</p>`).join('')||'<p class="muted">No files attached.</p>'}<h2>IoT snapshot</h2><p>${pill(e.telemetry.status)}</p>${e.telemetry.reading?`<p>Observed ${date(e.telemetry.reading.observed_at)} · ${e.telemetry.reading.running_hours??'—'} running hours · ${e.telemetry.reading.cycle_count??'—'} cycles · Alarm ${esc(e.telemetry.reading.alarm_code||'none')}</p>`:'<p class="muted">No readings available.</p>'}</div><div class="panel"><h2>Equipment label</h2><div class="qr">${qrSvg(e.qr_code)}</div><p><b>${esc(e.qr_code)}</b></p><p class="muted">Print this label and attach it to the machine. The code is an asset lookup identifier, not a credential.</p></div></div><div id="form-slot"></div>`;}
const field=(name,label,type='text',value='',extra='')=>type==='textarea'?`<label>${esc(label)}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`:`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,options)=>`<label>${esc(label)}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`;
const option=(list,label)=>list.map(x=>[x.id,x[label]||x.id]);
function form(title,kind,fields){$('#form-slot').innerHTML=`<div class="panel"><h2>${esc(title)}</h2><form data-form="${kind}" class="form-grid">${fields}<div class="form-actions"><button>Save</button>${btn('Cancel','cancel','secondary')}</div></form></div>`;$('#form-slot form').onsubmit=submit;document.querySelector('#form-slot [data-action="cancel"]').onclick=()=>{$('#form-slot').innerHTML=''};$('#form-slot').scrollIntoView({behavior:'smooth'});}
function action(name,id){state.error='';state.notice='';if(name==='logout'){state.token=null;state.user=null;render();return}if(name==='back'){state.detail=null;render();return}if(name==='cancel'){render();return}if(name==='ticket'||name==='equipment'){api(`/${name==='ticket'?'tickets':'equipment'}/${id}`).then(v=>{state.detail={type:name,value:v};render()}).catch(e=>message(e.message,true));return}if(name.startsWith('done:')){api('/checklist/'+name.split(':')[1],'PATCH',{done:true}).then(()=>refreshDetail('Checklist updated')).catch(e=>message(e.message,true));return}if(name.startsWith('visitDone:')){api('/visits/'+name.split(':')[1],'PATCH',{status:'completed'}).then(()=>{state.notice='Visit completed';load()}).catch(e=>message(e.message,true));return}if(name.startsWith('approve:')){const p=state.data.providers.find(x=>x.id===name.split(':')[1]);api(`/providers/${p.id}/approval`,'PATCH',{approved:!p.approved}).then(()=>load()).catch(e=>message(e.message,true));return}if(name.startsWith('fulfil:')){api(`/parts/${name.split(':')[1]}/fulfil`,'POST',{}).then(()=>{state.notice='Part fulfilled';load()}).catch(e=>message(e.message,true));return}if(name.startsWith('quotes:')){api(`/parts/${name.split(':')[1]}/quotes`).then(q=>{const p=state.data.parts.find(x=>x.id===name.split(':')[1]);$('#form-slot').innerHTML=`<div class="panel"><h2>Quotes for ${esc(p.item)}</h2>${q.map(x=>`<p>${(x.amount_minor/100).toFixed(2)} ${esc(x.currency)} · ${x.lead_days} days · ${pill(x.status)} ${customer()&&['customer_admin','plant_manager'].includes(state.user.role)&&x.status==='pending'?btn('Approve','decide:'+x.id):''}</p>`).join('')||'No quotes yet'}</div>`;document.querySelectorAll('[data-action^="decide:"]').forEach(b=>b.onclick=()=>action(b.dataset.action))}).catch(e=>message(e.message,true));return}if(name.startsWith('decide:')){api(`/quotes/${name.split(':')[1]}/decision`,'POST',{decision:'approved'}).then(()=>{state.notice='Quote approved';load()}).catch(e=>message(e.message,true));return}
  const d=state.data,t=state.detail?.value,e=state.detail?.value;
  if(name==='newTicket')return form('Raise breakdown ticket','ticket',select('equipmentId','Equipment',option(d.equipment,'model'))+field('title','Issue title')+select('priority','Priority',['low','medium','high','critical'].map(x=>[x,x]))+field('symptoms','Symptoms','textarea')+field('errorCodes','Error codes')+field('productionImpact','Production impact','textarea'));
  if(name==='newEquipment')return form('Add equipment','equipment',select('plantId','Plant',option(d.plants,'name'))+select('machineType','Machine type',['injection','blow','extrusion','mould','auxiliary'].map(x=>[x,x]))+field('make','Make')+field('model','Model')+field('serialNumber','Serial number')+field('location','Location'));
  if(name==='newContract')return form('New annual contract','contract',select('companyId','Company',option(d.companies,'name'))+field('title','Contract title')+field('startsAt','Start date','date')+field('renewsAt','Renewal date','date')+`<label class="wide">Covered equipment${d.equipment.map(x=>`<span style="display:block"><input type="checkbox" name="equipmentIds" value="${esc(x.id)}" style="width:auto"> ${esc(x.make)} ${esc(x.model)}</span>`).join('')}</label>`+field('visitAt','First scheduled visit for first selected asset','datetime-local')+field('commitments','Service commitments','textarea')+field('exclusions','Exclusions','textarea'));
  if(name==='newCompany')return form('Add customer company','company',field('name','Name')+field('timezone','IANA timezone','text','UTC')+field('currency','ISO currency code','text','USD')+select('units','Units',[['metric','Metric'],['imperial','Imperial']])+field('locale','Locale','text','en'));
  if(name==='newPlant')return form('Add plant','plant',select('companyId','Company',option(d.companies,'name'))+field('name','Name')+field('address','Address')+field('country','Country code','text','US')+field('serviceArea','Service area')+field('timezone','Timezone','text','UTC'));
  if(name==='newUser')return form('Add user','user',(state.user.role==='provider_admin'?select('providerId','Provider',option(d.providers,'name')):select('companyId','Company',option(d.companies,'name'))+(state.user.role==='platform_admin'?select('providerId','Provider for provider roles',[['','None'],...option(d.providers,'name')]):''))+field('name','Name')+field('email','Email','email')+select('role','Role',state.user.role==='provider_admin'?[['provider_engineer','Provider engineer']]:state.user.role==='platform_admin'?['customer_admin','plant_manager','maintenance','dispatcher','engineer','provider_admin','provider_engineer'].map(x=>[x,x]):['plant_manager','maintenance'].map(x=>[x,x]))+field('password','Temporary password','password')+(state.user.role==='platform_admin'||state.user.role==='provider_admin'?field('serviceAreas','Service areas (comma separated)')+field('skills','Machine skills (comma separated)'):''));
  if(name==='newProvider')return form('Add provider','provider',field('name','Name')+field('serviceAreas','Service areas (comma separated)')+field('skills','Skills (comma separated)'));
  if(name==='status')return form('Update ticket status','status',select('status','New status',['accepted','in_progress','escalated','completed'].map(x=>[x,x]))+field('downtimeMinutes','Total downtime in minutes','number',t.downtime_minutes)+field('note','Update note','textarea'));
  if(name==='assign')return form('Assign ticket','assign',select('assignee','Engineer or approved provider',[...(d.users||[]).filter(x=>x.role==='engineer').map(x=>['engineer:'+x.id,'Engineer: '+x.name]),...(d.providers||[]).filter(x=>x.approved).map(x=>['provider:'+x.id,'Provider: '+x.name])])) ;
  if(name==='checklist')return form('Add checklist item','checklist',field('item','Inspection item')+field('note','Note'));
  if(name==='workLog')return form('Log service work','workLog',field('description','Work performed','textarea')+field('minutes','Minutes','number')+field('partsUsed','Parts used'));
  if(name==='part')return form('Request spare part','part',field('item','Part description')+field('quantity','Quantity','number','1'));
  if(name==='signoff')return form('Customer sign-off','signoff',field('signerName','Signer name','text',state.user.name));
  if(name.startsWith('quote:'))return form('Create quotation','quote:'+name.split(':')[1],field('amountMinor','Amount in minor currency units','number')+field('currency','ISO currency code','text','USD')+field('leadDays','Lead time in days','number','3'));
  if(name==='attachment')return form('Attach file','attachment',select('kind','Type',(state.detail.type==='equipment'?['manual','photo']:['photo','evidence']).map(x=>[x,x]))+`<label class="wide">PDF or image (max 5 MB)<input name="file" type="file" accept=".pdf,image/png,image/jpeg,image/webp" required></label>`);
}
async function refreshDetail(text){if(state.detail){state.detail.value=await api(`/${state.detail.type==='ticket'?'tickets':'equipment'}/${state.detail.value.id}`);}state.notice=text;await load();}
async function submit(ev){ev.preventDefault();const form=ev.target,kind=form.dataset.form,f=new FormData(form),v=Object.fromEntries(f);try{let path='',body={},method='POST';if(kind==='ticket'){path='/tickets';body={...v}}else if(kind==='equipment'){path='/equipment';body={...v}}else if(kind==='contract'){path='/contracts';const equipmentIds=f.getAll('equipmentIds');body={companyId:v.companyId,title:v.title,startsAt:v.startsAt,renewsAt:v.renewsAt,commitments:v.commitments,exclusions:v.exclusions,equipmentIds,visits:v.visitAt&&equipmentIds.length?[{equipmentId:equipmentIds[0],dueAt:v.visitAt}]:[]}}else if(kind==='company'){path='/companies';body=v}else if(kind==='plant'){path='/plants';body=v}else if(kind==='user'){path='/users';body=v;if(['dispatcher','engineer'].includes(v.role))delete body.companyId;if(['provider_admin','provider_engineer'].includes(v.role))delete body.companyId;else delete body.providerId;body.serviceAreas=(v.serviceAreas||'').split(',').map(x=>x.trim()).filter(Boolean);body.skills=(v.skills||'').split(',').map(x=>x.trim()).filter(Boolean)}else if(kind==='provider'){path='/providers';body={name:v.name,serviceAreas:v.serviceAreas.split(',').map(x=>x.trim()).filter(Boolean),skills:v.skills.split(',').map(x=>x.trim()).filter(Boolean)}}else if(kind==='status'){path=`/tickets/${state.detail.value.id}/status`;body={...v,downtimeMinutes:Number(v.downtimeMinutes)}}else if(kind==='assign'){path=`/tickets/${state.detail.value.id}/assign`;const [assigneeType,assigneeId]=v.assignee.split(':');body={assigneeType,assigneeId}}else if(kind==='checklist'){path=`/tickets/${state.detail.value.id}/checklist`;body=v}else if(kind==='workLog'){path=`/tickets/${state.detail.value.id}/work-logs`;body={...v,minutes:Number(v.minutes)}}else if(kind==='part'){path=`/tickets/${state.detail.value.id}/parts`;body={...v,quantity:Number(v.quantity)}}else if(kind==='signoff'){path=`/tickets/${state.detail.value.id}/signoff`;body=v}else if(kind.startsWith('quote:')){path=`/parts/${kind.split(':')[1]}/quote`;body={amountMinor:Number(v.amountMinor),currency:v.currency,leadDays:Number(v.leadDays)}}else if(kind==='attachment'){const file=f.get('file');if(file.size>5*1024*1024)throw Error('File exceeds 5 MB');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});path='/attachments';body={entityType:state.detail.type,entityId:state.detail.value.id,kind:v.kind,filename:file.name,mime:file.type,base64}}await api(path,method,body);state.notice='Saved successfully';if(state.detail)await refreshDetail(state.notice);else await load();}catch(e){message(e.message,true)}}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-download]');if(!a)return;e.preventDefault();try{const r=await fetch(a.href,{headers:{authorization:`Bearer ${state.token}`}});if(!r.ok)throw Error('Unable to download');const blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=a.textContent;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){message(err.message,true)}});
render();
