import { qrSvg } from './qr.js';
import { t, label, setLocale, LOCALES, formatDateTime, formatDate, formatNumber, formatMoney, toMinorUnits, formatTemperature, formatDuration } from './shared/i18n.js';
import { signaturePad } from './shared/signature.js';

const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={token:null,user:null,page:'dashboard',detail:null,notice:'',error:'',data:{},pad:null};
const is=(...roles)=>roles.includes(state.user.role);
const customer=()=>is('customer_admin','plant_manager','maintenance'), internal=()=>is('platform_admin','dispatcher','engineer'), provider=()=>is('provider_admin','provider_engineer');
const manager=()=>is('platform_admin','customer_admin'), dispatch=()=>is('platform_admin','dispatcher'), deviceAdmin=()=>is('platform_admin','dispatcher','customer_admin'), fieldWorker=()=>internal()||provider();
const prefs=()=>state.user.preferences;
const btn=(text,action,cls='',id='')=>`<button class="${cls}" data-action="${action}"${id?` data-id="${esc(id)}"`:''}>${esc(text)}</button>`;
const pill=(group,value)=>`<span class="pill ${esc(value)}">${esc(label(group,value))}</span>`;
const plantOf=id=>(state.data.plants||[]).find(p=>p.id===id), companyOf=id=>(state.data.companies||[]).find(c=>c.id===id);
const when=(iso,zone=prefs().timezone)=>formatDateTime(iso,zone);
const assetName=id=>{ const e=(state.data.equipment||[]).find(x=>x.id===id); return e?`${e.make} ${e.model}`:'—'; };
const assigneeName=tk=>tk.assigned_provider_id?((state.data.providers||[]).find(p=>p.id===tk.assigned_provider_id)?.name||label('status','assigned')):tk.assigned_user_id?((state.data.users||[]).find(u=>u.id===tk.assigned_user_id)?.name||label('status','assigned')):t('label.unassigned');
const TRANSITIONS={assigned:['accepted','declined','escalated'],accepted:['in_progress','escalated'],in_progress:['escalated','completed'],escalated:['in_progress','completed']};

const api=async(path,method='GET',body)=>{const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json',...(state.token?{authorization:`Bearer ${state.token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(r.status===401&&state.token){state.token=null;state.user=null;}if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;};
function message(text,isError=false){state.notice=isError?'':text;state.error=isError?text:'';render();}
const fail=e=>message(e.message,true);
async function load(){const paths=['dashboard','companies','plants','equipment','tickets','contracts','parts','providers','users',...(manager()?['audit']:[]),...(deviceAdmin()?['devices']:[]),...(is('platform_admin')?['integrations/status']:[])];const out=await Promise.all(paths.map(async p=>[p==='integrations/status'?'integrations':p,await api('/'+p).catch(()=>[])]));state.data=Object.fromEntries(out);render();}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">${esc(t('msg.noRecords'))}</td></tr>`}</tbody></table></div>`;}
const tile=(text,value,tone='')=>`<div class="card ${tone}"><small>${esc(text)}</small><strong>${value}</strong></div>`;

function loginView(){$('#app').innerHTML=`<div class="login"><div class="brand" style="color:#12323d">Mould<span>Care</span></div><h1>Service operations</h1><p class="muted">Sign in to the local demo.</p><form id="login"><label>${t('label.email')}</label><input name="email" type="email" required value="acme@demo.test"><label>${t('label.password')}</label><input name="password" type="password" required value="DemoPass123!"><button>${t('action.signIn')}</button></form><p class="muted">Try admin@, dispatch@, engineer@, acme@, maint@, nova@, atlas-admin@, atlas@ or euro@demo.test. All use DemoPass123!</p>${state.error?`<p class="notice error">${esc(state.error)}</p>`:''}</div>`;$('#login').onsubmit=async e=>{e.preventDefault();try{const r=await api('/auth/login','POST',Object.fromEntries(new FormData(e.target)));state.token=r.token;state.user=r.user;setLocale(r.user.preferences.locale);state.error='';await load();}catch(err){message(err.message,true)}};}
function layout(content){
  const nav=['dashboard','tickets','equipment','contracts','parts','organisation','providers','integrations','audit','account'].filter(p=>({organisation:manager()||is('provider_admin'),providers:internal()||provider(),integrations:deviceAdmin(),audit:manager()})[p]??true);
  $('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand">Mould<span>Care</span></div>${nav.map(p=>`<button class="nav ${state.page===p&&!state.detail?'active':''}" data-nav="${p}">${esc(t('nav.'+p))}</button>`).join('')}<div class="profile"><b>${esc(state.user.name)}</b><br>${esc(label('role',state.user.role))}<br><label class="lang">${t('label.language')} <select id="locale">${Object.entries(LOCALES).map(([k,v])=>`<option value="${k}" ${prefs().locale===k?'selected':''}>${v}</option>`).join('')}</select></label><a class="click" data-action="logout">${t('action.signOut')}</a></div></aside><main class="main"><div class="top"><div><h1>${esc(state.detail?'':t('nav.'+state.page))}</h1><div class="muted">${t('app.tagline')}</div></div><div class="muted">${formatDate(new Date().toISOString(),prefs().timezone)} · ${esc(prefs().timezone)}</div></div>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}${content}</main></div>`;
  document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>{state.page=el.dataset.nav;state.detail=null;state.error='';state.notice='';render()});
  document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action,el.dataset.id));
  $('#locale').onchange=e=>api('/me','PATCH',{locale:e.target.value}).then(me=>{state.user=me;setLocale(me.preferences.locale);render()}).catch(fail);
}
function render(){if(!state.user)return loginView();const content=state.detail?.type==='ticket'?ticketDetail():state.detail?.type==='equipment'?assetDetail():({dashboard:overview,tickets,equipment,contracts,parts,organisation,providers,integrations:integrationsView,audit:auditView,account}[state.page]||overview)();layout(content);bindForms();}

function overview(){
  const d=state.data.dashboard||{}, tm=d.telemetry, list=(items,fn)=>items?.length?items.map(fn).join(''):`<p class="muted">${t('dash.none')}</p>`;
  const iot=tm&&(customer()||dispatch())?`<div class="grid" style="margin-top:16px">${tile(t('dash.reporting'),tm.current)}${tile(t('dash.staleData'),tm.stale+tm.missing,tm.stale+tm.missing?'warn':'')}${tile(t('dash.noDevice'),tm.unmapped)}${tile(t('dash.alarms'),tm.activeAlarms,tm.activeAlarms?'alert':'')}</div>`:'';
  return `<div class="grid">${tile(t('dash.open'),d.openTickets??0)}${tile(t('dash.unassigned'),d.unassigned??0,d.unassigned?'warn':'')}${tile(t('dash.breaches'),d.responseBreaches??0,d.responseBreaches?'alert':'')}${tile(t('dash.escalated'),d.escalated??0,d.escalated?'warn':'')}</div><div class="grid" style="margin-top:16px">${tile(t('dash.meanResponse'),formatDuration(d.averageResponseMinutes))}${tile(t('dash.downtime'),formatDuration(d.downtimeMinutes||0))}${tile(t('dash.repeat'),d.repeatFaultAssets||0,d.repeatFaultAssets?'warn':'')}${tile(t('dash.renewalsDue'),(d.upcomingRenewals||[]).length,(d.upcomingRenewals||[]).length?'warn':'')}</div>${iot}
  <div class="detail"><div><div class="panel"><h2>${t('dash.activeWork')}</h2>${table([t('nav.tickets'),t('label.priority'),t('label.status'),t('label.impact')],(d.tickets||[]).map(tk=>`<tr><td><a data-action="ticket" data-id="${esc(tk.id)}">${esc(tk.title)}</a></td><td>${pill('priority',tk.priority)}</td><td>${pill('status',tk.status)}</td><td>${esc(tk.production_impact)}</td></tr>`))}</div>
  <div class="panel"><h2>${t('dash.repeatFaults')}</h2>${list(d.repeatFaults,x=>`<div class="spread mini"><a data-action="equipment" data-id="${esc(x.equipmentId)}">${esc(x.label)}</a><b>${x.value}</b></div>`)}<h2 style="margin-top:18px">${t('dash.downtimeByAsset')}</h2>${list(d.downtimeByAsset,x=>`<div class="spread mini"><span>${esc(x.label)}</span><b>${formatDuration(x.value)}</b></div><div class="bar"><span style="width:${Math.round(x.value/d.downtimeByAsset[0].value*100)}%"></span></div>`)}</div></div>
  <div><div class="panel"><h2>${t('dash.responseByPriority')}</h2>${Object.entries(d.responseByPriority||{}).map(([p,m])=>`<div class="spread mini"><span>${pill('priority',p)} ${d.byPriority?.[p]??0} ${esc(label('status','open').toLowerCase())}</span><b>${formatDuration(m)}</b></div>`).join('')}${d.breachedTickets?.length?`<h2 style="margin-top:18px">${t('dash.breaches')}</h2>${d.breachedTickets.map(x=>`<p class="mini">${pill('priority',x.priority)} <a data-action="ticket" data-id="${esc(x.id)}">${esc(x.title)}</a></p>`).join('')}`:''}</div>
  <div class="panel"><h2>${t('dash.upcoming')}</h2>${list(d.upcomingMaintenance,v=>`<p class="mini">${esc(v.make)} ${esc(v.model)}<br>${when(v.due_at,v.timezone)}</p>`)}${d.overdueVisits?.length?`<h2>${t('dash.overdue')}</h2>${d.overdueVisits.map(v=>`<p class="mini overdue">${esc(v.make)} ${esc(v.model)}<br>${when(v.due_at,v.timezone)}</p>`).join('')}`:''}<h2>${t('dash.renewals')}</h2>${list(d.upcomingRenewals,c=>`<p class="mini">${esc(c.title)}<br>${formatDate(c.renews_at)}</p>`)}</div></div></div>`;
}
function tickets(){const list=state.data.tickets||[];return `<div class="panel spread"><div><h2>${t('nav.tickets')}</h2><span class="muted">${list.length}</span></div>${customer()||internal()?btn(t('action.raiseTicket'),'newTicket'):''}</div><div class="panel">${table([t('nav.tickets'),t('label.asset'),t('label.priority'),t('label.status'),t('label.opened'),t('label.assignment')],list.map(tk=>`<tr><td><a data-action="ticket" data-id="${esc(tk.id)}">${esc(tk.title)}</a><div class="muted">${esc(tk.error_codes)}</div></td><td>${esc(assetName(tk.equipment_id))}</td><td>${pill('priority',tk.priority)}</td><td>${pill('status',tk.status)}</td><td>${when(tk.created_at,plantOf(tk.plant_id)?.timezone)}</td><td>${esc(assigneeName(tk))}</td></tr>`))}</div><div id="form-slot"></div>`;}
function equipment(){const list=state.data.equipment||[];return `<div class="panel spread"><div><h2>${t('nav.equipment')}</h2><span class="muted">${list.length}</span></div>${manager()?btn('Add equipment','newEquipment'):''}</div><div class="panel">${table([t('label.asset'),'Type','Serial','Location','Plant'],list.map(e=>`<tr><td><a data-action="equipment" data-id="${esc(e.id)}">${esc(e.make)} ${esc(e.model)}</a></td><td>${pill('machine',e.machine_type)}</td><td>${esc(e.serial_number)}</td><td>${esc(e.location)}</td><td>${esc(plantOf(e.plant_id)?.name||'')}</td></tr>`))}</div><div id="form-slot"></div>`;}
function contracts(){
  const list=state.data.contracts||[], canEdit=manager()||is('dispatcher'), zone=equipmentId=>plantOf((state.data.equipment||[]).find(e=>e.id===equipmentId)?.plant_id)?.timezone;
  return `<div class="panel spread"><h2>${t('nav.contracts')}</h2>${canEdit?btn('New contract','newContract'):''}</div>${list.map(c=>`<div class="panel"><div class="spread"><h2>${esc(c.title)}</h2><span>${c.status==='active'&&c.daysToRenewal<=90?`<span class="pill stale">${t('label.renews')}: ${c.daysToRenewal} ${t('label.days')}</span> `:''}${pill('status',c.status)}</span></div><div class="grid"><div><small>${t('label.starts')}</small><p>${formatDate(c.starts_at)}</p></div><div><small>${t('label.renews')}</small><p>${formatDate(c.renews_at)}</p></div><div><small>${t('label.responseTarget')}</small><p>${c.response_hours?c.response_hours+' '+t('label.hours'):'—'}</p></div><div><small>${t('nav.equipment')}</small><p>${c.equipmentIds.map(id=>esc(assetName(id))).join(', ')}</p></div></div><p><b>${t('label.commitments')}:</b> ${esc(c.commitments)}</p><p><b>${t('label.exclusions')}:</b> ${esc(c.exclusions)}</p><h2>${t('label.visits')}</h2>${c.visits.map(v=>`<div class="mini spread"><span>${when(v.due_at,zone(v.equipment_id))} · ${esc(assetName(v.equipment_id))} · ${esc(v.notes)}</span><span>${pill('status',v.status)} ${v.status==='scheduled'&&canEdit?btn(label('status','completed'),'visitDone','secondary',v.id):''}</span></div>`).join('')||`<p class="muted">${t('dash.none')}</p>`}${canEdit&&c.status==='active'?`<div class="section-actions">${btn(t('action.addVisit'),'addVisit','secondary',c.id)}${btn(t('action.extend'),'renewal','secondary',c.id)}</div>`:''}</div>`).join('')||`<div class="panel empty">${t('msg.noRecords')}</div>`}<div id="form-slot"></div>`;
}
function parts(){
  const list=state.data.parts||[], step={approved:['ordered','shipped','fulfilled'],ordered:['shipped','fulfilled'],shipped:['fulfilled']};
  return `<div class="panel"><h2>${t('nav.parts')}</h2>${table(['Part',t('nav.tickets'),'Qty',t('label.status'),t('action.quote'),t('label.reference'),''],list.map(p=>`<tr><td>${esc(p.item)}</td><td><a data-action="ticket" data-id="${esc(p.ticket_id)}">${esc(p.ticketTitle)}</a></td><td>${p.quantity}</td><td>${pill('status',p.status)}</td><td>${p.quote?`${formatMoney(p.quote.amount_minor,p.quote.currency)}<div class="muted">${p.quote.lead_days} ${t('label.days')} · ${esc(label('status',p.quote.status))}</div>`:'—'}</td><td>${esc(p.fulfilment_reference||'')}</td><td class="row">${btn(t('action.viewQuotes'),'quotes','secondary',p.id)}${internal()&&['requested','quoted','rejected'].includes(p.status)?btn(t('action.quote'),'quote','',p.id):''}${internal()?(step[p.status]||[]).map(s=>btn(label('status',s),'fulfil:'+s,'secondary',p.id)).join(''):''}</td></tr>`))}</div><div id="form-slot"></div>`;
}
function organisation(){
  const users=state.data.users||[], canManage=x=>is('platform_admin')||(is('customer_admin')&&x.company_id===state.user.companyId&&['plant_manager','maintenance'].includes(x.role))||(is('provider_admin')&&x.provider_id===state.user.providerId&&x.role==='provider_engineer');
  return `<div class="section-actions">${is('platform_admin')?btn('Add company','newCompany'):''}${manager()?btn('Add plant','newPlant'):''}${manager()||is('provider_admin')?btn('Add user','newUser'):''}</div>${(state.data.companies||[]).length?`<div class="panel"><h2>Companies</h2>${table(['Name','Time zone','Currency','Units',t('label.language')],state.data.companies.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.timezone)}</td><td>${esc(c.currency)}</td><td>${esc(c.units)}</td><td>${esc(LOCALES[c.locale]||c.locale)}</td></tr>`))}</div><div class="panel"><h2>Plants</h2>${table(['Name','Country','Service area','Time zone'],(state.data.plants||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.country)}</td><td>${esc(p.service_area)}</td><td>${esc(p.timezone)}</td></tr>`))}</div>`:''}<div class="panel"><h2>Users</h2>${table(['Name',t('label.email'),'Role',t('label.status'),''],users.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${pill('role',x.role)}</td><td>${pill('status',x.active?'active':'inactive')}</td><td>${canManage(x)&&x.id!==state.user.id?btn(x.active?t('action.deactivate'):t('action.activate'),'userActive','secondary',x.id):''}</td></tr>`))}</div><div id="form-slot"></div>`;
}
function providers(){const list=state.data.providers||[];return `<div class="panel spread"><h2>${t('nav.providers')}</h2>${is('platform_admin')?btn('Add provider','newProvider'):''}</div><div class="panel">${table(['Provider','Approved','Areas','Skills',''],list.map(p=>`<tr><td>${esc(p.name)}</td><td>${pill('status',p.approved?'approved':'pending')}</td><td>${esc(JSON.parse(p.service_areas).join(', '))}</td><td>${JSON.parse(p.skills).map(s=>esc(label('machine',s))).join(', ')}</td><td>${is('platform_admin')?btn(p.approved?'Suspend':t('action.approve'),'approveProvider','secondary',p.id):''}</td></tr>`))}</div><div id="form-slot"></div>`;}
function auditView(){return `<div class="panel"><h2>${t('nav.audit')}</h2>${table(['Time','Action','Entity','Actor'],(state.data.audit||[]).map(a=>`<tr><td>${when(a.created_at)}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type)} ${esc(a.entity_id)}</td><td>${esc((state.data.users||[]).find(x=>x.id===a.actor_id)?.name||a.actor_id)}</td></tr>`))}</div>`;}
function account(){const p=prefs();return `<div class="detail"><div class="panel"><h2>${t('nav.account')}</h2><p>${esc(state.user.name)} · ${esc(state.user.email)} · ${esc(label('role',state.user.role))}</p><p class="muted">Time zone ${esc(p.timezone)} · currency ${esc(p.currency)} · units ${esc(p.units)} · ${t('label.language')} ${esc(LOCALES[p.locale])}</p><p class="muted">Time zone, currency and units come from your company. Ticket and visit times are shown in the plant's local time.</p></div><div class="panel"><h2>Change password</h2><form data-form="password" class="form-grid">${field('currentPassword','Current password','password','','required autocomplete="current-password"')}${field('newPassword','New password (12+ characters)','password','','required minlength="12" autocomplete="new-password"')}<div class="form-actions"><button>${t('action.save')}</button></div></form></div></div>`;}
function integrationsView(){const s=state.data.integrations||{},devices=state.data.devices||[];return `${s.runs?`<div class="panel spread"><div><h2>Machine data sync</h2><span class="muted">Adapter: ${esc(s.adapter)} · cursor ${esc(s.cursors?.[0]?.cursor||'none')} · API keys stay on the server</span></div>${btn(t('action.syncNow'),'runSync')}</div>`:''}<div class="panel"><h2>Device mappings</h2><p class="muted">Each external device ID is bound to one asset and company. Unmapped or inactive devices are rejected. Map new devices from an asset's page.</p>${table(['Device',t('label.asset'),'Stale after',t('label.status'),''],devices.map(x=>`<tr><td>${esc(x.external_device_id)}</td><td><a data-action="equipment" data-id="${esc(x.equipment_id)}">${esc(x.make)} ${esc(x.model)}</a></td><td>${x.stale_after_minutes} min</td><td>${pill('status',x.active?'active':'inactive')}</td><td>${btn(x.active?t('action.deactivate'):t('action.activate'),'deviceActive','secondary',x.id)}</td></tr>`))}</div>${s.runs?`<div class="panel"><h2>Recent sync runs</h2>${table(['Started',t('label.status'),'Accepted','Duplicate','Rejected','Error'],s.runs.map(r=>`<tr><td>${when(r.started_at)}</td><td>${pill('status',r.status)}</td><td>${r.accepted}</td><td>${r.duplicates}</td><td>${r.rejected}</td><td>${esc(r.error||'')}</td></tr>`))}</div><div class="panel"><h2>Quarantined records</h2><p class="muted">Rejected payloads are kept for review and never attached to an asset.</p>${table(['Received','Source','Device','Reasons'],s.rejections.map(r=>`<tr><td>${when(r.received_at)}</td><td>${esc(r.source)}</td><td>${esc(r.external_device_id||'—')}</td><td>${r.reasons.map(esc).join('<br>')}</td></tr>`))}</div>`:''}`;}
function telemetryPanel(e){
  const tm=e.telemetry, units=companyOf(e.company_id)?.units||prefs().units, names={runningHours:'Running hours',cycleCount:'Cycle count',temperatureC:'Temperature'}, value=(k,v)=>v==null?'—':k==='temperatureC'?formatTemperature(v,units):formatNumber(v,1);
  const summary={unmapped:'No device is mapped to this asset.',inactive:'Device mapping is inactive; readings are not accepted.',missing:'Device mapped, but no readings received yet.',stale:`No reading for ${formatDuration(tm.ageMinutes)} (stale after ${tm.staleAfterMinutes} min). Values below may be out of date.`,current:`Last reading ${formatDuration(tm.ageMinutes)} ago · stale after ${tm.staleAfterMinutes} min`}[tm.status];
  return `<div class="spread"><h2>${t('section.machineData')}</h2>${pill('status',tm.status)}</div><p class="muted">${summary}${tm.deviceIds.length?` · Device ${tm.deviceIds.map(esc).join(', ')}`:''}</p>${tm.metrics?table(['Metric','Last value','Observed',t('label.status')],Object.entries(names).map(([k,n])=>{const m=tm.metrics[k];return `<tr><td>${n}</td><td>${value(k,m.value)}</td><td>${m.observedAt?when(m.observedAt,e.plant?.timezone):'Never reported'}</td><td>${pill('status',m.status)}</td></tr>`})):''}${tm.activeAlarms.length?`<h2 style="margin-top:16px">${t('dash.alarms')}</h2>${tm.activeAlarms.map(a=>`<p>${pill('severity',a.severity)} <b>${esc(a.code)}</b> ${esc(a.message)} <span class="muted">${when(a.raised_at,e.plant?.timezone)}</span></p>`).join('')}`:''}`;
}
function ticketDetail(){
  const tk=state.detail.value, zone=tk.plant?.timezone, assignee=is('engineer','provider_admin','provider_engineer');
  const files=list=>list.map(a=>`<p><a href="/api/attachments/${esc(a.id)}" data-download="${esc(a.id)}">${esc(a.filename)}</a> · ${esc(a.kind)}</p>`).join('');
  const signoff=tk.signoff?`${esc(t('msg.signedBy',{name:tk.signoff.signer_name,date:when(tk.signoff.signed_at,zone)}))}${tk.signoff.method==='on_site'?` <span class="muted">(${t('msg.signedOnSite')})</span>`:''}`:esc(t('msg.awaitingSignoff'));
  const cov=tk.coverage?`<p><b>${esc(tk.coverage.title)}</b></p><p class="mini">${t('label.commitments')}: ${esc(tk.coverage.commitments)}<br>${t('label.exclusions')}: ${esc(tk.coverage.exclusions)}</p>${tk.responseDueAt?`<p>${t('label.responseDue')}: ${when(tk.responseDueAt,zone)} ${tk.responseBreached?`<span class="pill critical">${t('msg.breached')}</span>`:tk.first_response_at?`<span class="pill">${t('msg.onTrack')}</span>`:''}</p>`:''}`:`<p class="muted">${t('label.notCovered')}</p>`;
  return `<div class="section-actions">${btn('← '+t('nav.tickets'),'back','secondary')}${fieldWorker()&&TRANSITIONS[tk.status]?btn(t('action.updateStatus'),'status'):''}${fieldWorker()&&tk.status!=='completed'?btn(t('action.logWork'),'workLog')+btn(t('action.checklist'),'checklist','secondary'):''}${customer()||fieldWorker()?btn(t('action.requestPart'),'part','secondary'):''}${tk.status==='completed'&&!tk.signoff&&(customer()||fieldWorker())?btn(t('action.signoff'),'signoff'):''}${dispatch()&&tk.status!=='completed'?btn(t('action.assign'),'assign'):''}${btn(t('action.attach'),'attachment','secondary')}</div>
  <div class="detail"><div><div class="panel"><div class="spread"><h2>${esc(tk.title)}</h2>${pill('status',tk.status)}</div><p>${pill('priority',tk.priority)} · <a data-action="equipment" data-id="${esc(tk.equipment_id)}">${esc(tk.asset?.make)} ${esc(tk.asset?.model)}</a> · ${esc(tk.asset?.serial_number)} · ${esc(tk.plant?.name)} (${esc(zone)})</p><p><b>${t('label.symptoms')}:</b> ${esc(tk.symptoms)}</p><p><b>${t('label.errorCodes')}:</b> ${esc(tk.error_codes||'—')}</p><p><b>${t('label.impact')}:</b> ${esc(tk.production_impact)}</p><p><b>${t('label.downtime')}:</b> ${formatDuration(tk.downtime_minutes)} · <b>${t('label.opened')}:</b> ${when(tk.created_at,zone)}</p></div>
  <div class="panel"><h2>${t('section.checklist')}</h2>${tk.checklist.length?tk.checklist.map(c=>`<div class="check ${c.done?'done':''}"><span>${c.done?'☑':'☐'} ${esc(c.item)} <span class="muted">${esc(c.note)}</span></span>${fieldWorker()&&tk.status!=='completed'?btn(c.done?t('action.undo'):t('action.done'),c.done?'undo':'done','secondary',c.id):''}</div>`).join(''):`<p class="muted">${t('msg.noRecords')}</p>`}</div>
  <div class="panel"><h2>${t('section.work')}</h2>${tk.workLogs.length?tk.workLogs.map(w=>`<p>${esc(w.description)} <span class="muted">${formatDuration(w.minutes)} · ${esc(w.user_name)} · ${esc(w.parts_used)}</span></p>`).join(''):`<p class="muted">${t('msg.noRecords')}</p>`}${tk.parts.length?`<h2 style="margin-top:16px">${t('nav.parts')}</h2>${tk.parts.map(p=>`<p>${esc(p.item)} × ${p.quantity} ${pill('status',p.status)}</p>`).join('')}`:''}</div>
  <div class="panel"><h2>${t('section.evidence')}</h2>${files(tk.attachments)||`<p class="muted">${t('msg.noRecords')}</p>`}<p>${signoff}</p></div></div>
  <div><div class="panel"><h2>${t('label.coverage')}</h2>${cov}</div><div class="panel"><h2>${t('section.activity')}</h2>${tk.events.map(e=>`<p class="mini">${pill('status',e.event_type)} · ${esc(e.actor_name)}<br>${when(e.created_at,zone)}<br>${esc(e.detail)}</p>`).join('')}</div></div></div><div id="form-slot"></div>`;
}
function assetDetail(){
  const e=state.detail.value;
  return `<div class="section-actions">${btn('← '+t('nav.equipment'),'back','secondary')}${manager()||dispatch()?btn(t('action.edit'),'editEquipment','secondary'):''}${manager()?btn('Attach manual or photo','attachment'):''}${deviceAdmin()?btn('Map IoT device','mapDevice','secondary'):''}</div><div class="detail"><div><div class="panel"><h2>${esc(e.make)} ${esc(e.model)}</h2><p>${pill('machine',e.machine_type)} · Serial ${esc(e.serial_number)}</p><p>${esc(e.plant?.name)} · ${esc(e.location)}</p><h2>Manuals and photos</h2>${e.attachments.map(a=>`<p><a href="/api/attachments/${esc(a.id)}" data-download="${esc(a.id)}">${esc(a.filename)}</a> · ${esc(a.kind)}</p>`).join('')||`<p class="muted">${t('msg.noRecords')}</p>`}<h2>${t('nav.tickets')}</h2>${e.tickets.map(x=>`<p class="mini"><a data-action="ticket" data-id="${esc(x.id)}">${esc(x.title)}</a> ${pill('status',x.status)} · ${formatDate(x.created_at,e.plant?.timezone)}</p>`).join('')||`<p class="muted">${t('msg.noRecords')}</p>`}</div><div class="panel">${telemetryPanel(e)}</div></div><div class="panel"><h2>Equipment label</h2><div class="qr">${qrSvg(e.qr_code)}</div><p><b>${esc(e.qr_code)}</b></p><p class="muted">Print this label and attach it to the machine. The code is an asset lookup identifier, not a credential.</p></div></div><div id="form-slot"></div>`;
}

const field=(name,text,type='text',value='',extra='')=>type==='textarea'?`<label>${esc(text)}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`:`<label>${esc(text)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,text,options,selected='')=>`<label>${esc(text)}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
const option=(list,key)=>list.map(x=>[x.id,x[key]||x.id]);
function form(title,kind,fields,id=''){$('#form-slot').innerHTML=`<div class="panel"><h2>${esc(title)}</h2><form data-form="${kind}" data-id="${esc(id)}" class="form-grid">${fields}<div class="form-actions"><button>${t('action.save')}</button>${btn(t('action.cancel'),'cancel','secondary')}</div></form></div>`;bindForms();$('#form-slot [data-action="cancel"]').onclick=()=>{$('#form-slot').innerHTML='';state.pad=null};$('#form-slot').scrollIntoView({behavior:'smooth'});}
function bindForms(){document.querySelectorAll('form[data-form]').forEach(el=>el.onsubmit=submit);}
const later=(promise,text)=>promise.then(()=>refresh(text)).catch(fail);

async function action(name,id){
  state.error='';state.notice='';
  const d=state.data, tk=state.detail?.value;
  if(name==='logout'){state.token=null;state.user=null;state.detail=null;state.page='dashboard';return render()}
  if(name==='back'){state.detail=null;return render()}
  if(name==='ticket'||name==='equipment')return api(`/${name==='ticket'?'tickets':'equipment'}/${id}`).then(v=>{state.detail={type:name,value:v};render();window.scrollTo(0,0)}).catch(fail);
  if(name==='done'||name==='undo')return later(api('/checklist/'+id,'PATCH',{done:name==='done'}),t('msg.saved'));
  if(name==='visitDone')return later(api('/visits/'+id,'PATCH',{status:'completed'}),t('msg.saved'));
  if(name==='approveProvider'){const p=d.providers.find(x=>x.id===id);return later(api(`/providers/${id}/approval`,'PATCH',{approved:!p.approved}),t('msg.saved'))}
  if(name==='userActive'){const x=d.users.find(u=>u.id===id);return later(api('/users/'+id,'PATCH',{active:!x.active}),t('msg.saved'))}
  if(name==='deviceActive'){const x=d.devices.find(v=>v.id===id);return later(api('/devices/'+id,'PATCH',{active:!x.active}),t('msg.saved'))}
  if(name==='runSync')return api('/integrations/sync','POST',{}).then(r=>refresh(`Sync ${r.status}: ${r.accepted} accepted, ${r.duplicates} duplicate, ${r.rejected} rejected`)).catch(fail);
  if(name.startsWith('fulfil:')){const p=d.parts.find(x=>x.id===id);return form(`${label('status',name.slice(7))}: ${p.item}`,name,field('reference',t('label.reference')+' (PO, tracking or delivery note)','text',p.fulfilment_reference),id)}
  if(name==='quotes')return api(`/parts/${id}/quotes`).then(q=>{const p=d.parts.find(x=>x.id===id),canDecide=is('customer_admin','plant_manager');$('#form-slot').innerHTML=`<div class="panel"><h2>${t('action.viewQuotes')}: ${esc(p.item)}</h2>${q.map(x=>`<div class="spread mini"><span>${formatMoney(x.amount_minor,x.currency)} · ${x.lead_days} ${t('label.days')} · ${when(x.created_at)}</span><span>${pill('status',x.status)} ${canDecide&&x.status==='pending'?btn(t('action.approve'),'decide:approved','',x.id)+btn(t('action.reject'),'decide:rejected','secondary',x.id):''}</span></div>`).join('')||t('msg.noRecords')}</div>`;document.querySelectorAll('#form-slot [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))}).catch(fail);
  if(name.startsWith('decide:'))return later(api(`/quotes/${id}/decision`,'POST',{decision:name.slice(7)}),t('msg.saved'));
  if(name==='newTicket')return form(t('action.raiseTicket'),'ticket',select('equipmentId',t('label.asset'),d.equipment.map(e=>[e.id,`${e.make} ${e.model} · ${e.serial_number}`]))+field('title','Issue title','text','','required')+select('priority',t('label.priority'),['low','medium','high','critical'].map(x=>[x,label('priority',x)]),'high')+field('symptoms',t('label.symptoms'),'textarea','','required')+field('errorCodes',t('label.errorCodes'))+field('productionImpact',t('label.impact'),'textarea','','required'));
  if(name==='newEquipment')return form('Add equipment','equipment',select('plantId','Plant',option(d.plants,'name'))+select('machineType','Machine type',['injection','blow','extrusion','mould','auxiliary'].map(x=>[x,label('machine',x)]))+field('make','Make')+field('model','Model')+field('serialNumber','Serial number')+field('location','Location'));
  if(name==='editEquipment'){const e=state.detail.value;return form(t('action.edit'),'editEquipment',select('plantId','Plant',option(d.plants.filter(p=>p.company_id===e.company_id),'name'),e.plant_id)+field('make','Make','text',e.make)+field('model','Model','text',e.model)+field('serialNumber','Serial number','text',e.serial_number)+field('location','Location','text',e.location))}
  if(name==='newContract')return form('New annual contract','contract',select('companyId','Company',option(d.companies,'name'))+field('title','Contract title')+field('startsAt',t('label.starts'),'date')+field('renewsAt',t('label.renews'),'date')+field('responseHours',t('label.responseTarget')+' (hours)','number','8','min="1" max="720"')+`<label class="wide">${t('nav.equipment')}${d.equipment.map(x=>`<span style="display:block"><input type="checkbox" name="equipmentIds" value="${esc(x.id)}" style="width:auto"> ${esc(x.make)} ${esc(x.model)}</span>`).join('')}</label>`+field('visitAt','First scheduled visit for first selected asset (plant local time)','datetime-local')+field('commitments',t('label.commitments'),'textarea')+field('exclusions',t('label.exclusions'),'textarea'));
  if(name==='addVisit'){const c=d.contracts.find(x=>x.id===id);return form(`${t('action.addVisit')}: ${c.title}`,'visit',select('equipmentId',t('label.asset'),c.equipmentIds.map(e=>[e,assetName(e)]))+field('dueAt','Date and time (plant local time)','datetime-local','','required')+field('notes',t('label.note')),id)}
  if(name==='renewal'){const c=d.contracts.find(x=>x.id===id);return form(`${t('action.extend')}: ${c.title}`,'renewal',field('renewsAt',t('label.renews'),'date',c.renews_at.slice(0,10),'required')+field('responseHours',t('label.responseTarget')+' (hours)','number',c.response_hours??'','min="1" max="720"')+select('status',t('label.status'),['active','expired','cancelled'].map(x=>[x,label('status',x)]),c.status),id)}
  if(name==='newCompany')return form('Add customer company','company',field('name','Name')+field('timezone','IANA time zone','text','UTC')+field('currency','ISO currency code','text','USD')+select('units','Units',[['metric','Metric'],['imperial','Imperial']])+select('locale',t('label.language'),Object.entries(LOCALES)));
  if(name==='newPlant')return form('Add plant','plant',select('companyId','Company',option(d.companies,'name'))+field('name','Name')+field('address','Address')+field('country','Country code (ISO, 2 letters)','text','US')+field('serviceArea','Service area (e.g. US-MW)')+field('timezone','IANA time zone','text','UTC'));
  if(name==='newUser')return form('Add user','user',(is('provider_admin')?select('providerId','Provider',option(d.providers,'name')):select('companyId','Company',option(d.companies,'name'))+(is('platform_admin')?select('providerId','Provider for provider roles',[['','None'],...option(d.providers,'name')]):''))+field('name','Name')+field('email',t('label.email'),'email')+select('role','Role',(is('provider_admin')?['provider_engineer']:is('platform_admin')?['customer_admin','plant_manager','maintenance','dispatcher','engineer','provider_admin','provider_engineer']:['plant_manager','maintenance']).map(x=>[x,label('role',x)]))+field('password','Temporary password (12+ characters)','password')+(is('platform_admin','provider_admin')?field('serviceAreas','Service areas (comma separated)')+field('skills','Machine skills (comma separated: injection, blow, extrusion, mould, auxiliary)'):''));
  if(name==='newProvider')return form('Add provider','provider',field('name','Name')+field('serviceAreas','Service areas (comma separated)')+field('skills','Skills (comma separated)'));
  if(name==='status')return form(t('action.updateStatus'),'status',select('status',t('label.status'),TRANSITIONS[tk.status].filter(s=>s!=='declined'||is('engineer','provider_admin','provider_engineer')).map(x=>[x,label('status',x)]))+field('downtimeMinutes',`${t('label.downtime')} (${t('label.minutes')})`,'number',tk.downtime_minutes,'min="0"')+field('note',`${t('label.note')} — ${t('msg.noteRequired')}`,'textarea'));
  if(name==='assign')return api(`/tickets/${tk.id}/candidates`).then(list=>{const ok=list.filter(c=>c.eligible),no=list.filter(c=>!c.eligible);form(t('action.assign'),'assign',(ok.length?select('assignee','Eligible for this area and machine type',ok.map(c=>[`${c.type}:${c.id}`,`${c.type==='engineer'?'Engineer':'Provider'}: ${c.name} · ${c.openWork} open`])):'<p class="wide notice error">No eligible engineer or provider.</p>')+(no.length?`<div class="wide mini">Not eligible: ${no.map(c=>`${esc(c.name)} (${esc(c.reasons.join(', '))})`).join('; ')}</div>`:''))}).catch(fail);
  if(name==='checklist')return form(t('action.checklist'),'checklist',field('item','Inspection item','text','','required')+field('note',t('label.note')));
  if(name==='workLog')return form(t('action.logWork'),'workLog',field('description','Work performed','textarea','','required')+field('minutes',t('label.minutes'),'number','','required min="1"')+field('partsUsed','Parts used'));
  if(name==='part')return form(t('action.requestPart'),'part',field('item','Part description','text','','required')+field('quantity','Quantity','number','1','min="1"'));
  if(name==='signoff'){if(customer())return form(t('action.signoff'),'signoff',field('signerName',t('label.signerName'),'text',state.user.name,'required'));form(t('action.signoff'),'signoffOnSite',field('signerName',t('label.signerName'),'text','','required')+`<div class="wide"><label>${t('label.signature')}</label><canvas class="signature" id="sig"></canvas>${btn(t('action.clear'),'clearSig','secondary')}</div>`);state.pad=signaturePad($('#sig'));$('#form-slot [data-action="clearSig"]').onclick=e=>{e.preventDefault();state.pad.clear()};return}
  if(name==='quote'){const p=d.parts.find(x=>x.id===id),code=companyOf(p.company_id)?.currency||prefs().currency;return form(`${t('action.quote')}: ${p.item}`,'quote',field('amount','Amount (major units, e.g. 485.00)','number','','required min="0.01" step="0.01"')+field('currency','ISO currency code','text',code,'required')+field('leadDays','Lead time (days)','number','3','min="0"'),id)}
  if(name==='attachment')return form(t('action.attach'),'attachment',select('kind','Type',(state.detail.type==='equipment'?['manual','photo']:['photo','evidence']).map(x=>[x,x]))+`<label class="wide">PDF or image (max 5 MB)<input name="file" type="file" accept=".pdf,image/png,image/jpeg,image/webp" required></label>`);
  if(name==='mapDevice')return form('Map IoT device to this asset','device',field('externalDeviceId','External device ID (from the machine-data API)','text','','required')+field('staleAfterMinutes','Mark stale after (minutes)','number','30','min="1" max="10080"'));
}
async function refresh(text){if(state.detail)state.detail.value=await api(`/${state.detail.type==='ticket'?'tickets':'equipment'}/${state.detail.value.id}`).catch(()=>{state.detail=null});state.notice=text;await load();}
const fileBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
const list=v=>(v||'').split(',').map(x=>x.trim()).filter(Boolean);
async function submit(ev){
  ev.preventDefault();const formEl=ev.target,kind=formEl.dataset.form,id=formEl.dataset.id,f=new FormData(formEl),v=Object.fromEntries(f),tid=state.detail?.value?.id;
  try{
    let path,body=v,method='POST',done=t('msg.saved');
    if(kind==='ticket')path='/tickets';
    else if(kind==='equipment')path='/equipment';
    else if(kind==='editEquipment'){path='/equipment/'+tid;method='PATCH'}
    else if(kind==='contract'){const equipmentIds=f.getAll('equipmentIds');path='/contracts';body={companyId:v.companyId,title:v.title,startsAt:v.startsAt,renewsAt:v.renewsAt,responseHours:v.responseHours?Number(v.responseHours):null,commitments:v.commitments,exclusions:v.exclusions,equipmentIds,visits:v.visitAt&&equipmentIds.length?[{equipmentId:equipmentIds[0],dueAt:v.visitAt}]:[]}}
    else if(kind==='visit')path=`/contracts/${id}/visits`;
    else if(kind==='renewal'){path='/contracts/'+id;method='PATCH';body={renewsAt:v.renewsAt,status:v.status,responseHours:v.responseHours?Number(v.responseHours):null}}
    else if(kind==='company')path='/companies';
    else if(kind==='plant')path='/plants';
    else if(kind==='user'){path='/users';body={...v,serviceAreas:list(v.serviceAreas),skills:list(v.skills)};if(['provider_admin','provider_engineer'].includes(v.role))delete body.companyId;else delete body.providerId;if(['dispatcher','engineer'].includes(v.role))delete body.companyId}
    else if(kind==='provider'){path='/providers';body={name:v.name,serviceAreas:list(v.serviceAreas),skills:list(v.skills)}}
    else if(kind==='status'){path=`/tickets/${tid}/status`;body={...v,downtimeMinutes:Number(v.downtimeMinutes)};if(['declined','escalated'].includes(v.status)&&!v.note.trim())throw Error(t('msg.noteRequired'));if(v.status==='declined'){state.detail=null;done=t('msg.declined')}}
    else if(kind==='assign'){if(!v.assignee)throw Error('Choose an assignee');const [assigneeType,assigneeId]=v.assignee.split(':');path=`/tickets/${tid}/assign`;body={assigneeType,assigneeId}}
    else if(kind==='checklist')path=`/tickets/${tid}/checklist`;
    else if(kind==='workLog'){path=`/tickets/${tid}/work-logs`;body={...v,minutes:Number(v.minutes)}}
    else if(kind==='part'){path=`/tickets/${tid}/parts`;body={...v,quantity:Number(v.quantity)}}
    else if(kind==='signoff')path=`/tickets/${tid}/signoff`;
    else if(kind==='signoffOnSite'){if(!state.pad||state.pad.isEmpty())throw Error(t('msg.signFirst'));path=`/tickets/${tid}/signoff`;body={signerName:v.signerName,signatureBase64:state.pad.toBase64()}}
    else if(kind==='quote'){path=`/parts/${id}/quote`;body={amountMinor:toMinorUnits(v.amount,v.currency.toUpperCase()),currency:v.currency.toUpperCase(),leadDays:Number(v.leadDays)}}
    else if(kind.startsWith('fulfil:')){path=`/parts/${id}/fulfilment`;body={status:kind.slice(7),reference:v.reference}}
    else if(kind==='attachment'){const file=f.get('file');if(file.size>5*1024*1024)throw Error('File exceeds 5 MB');path='/attachments';body={entityType:state.detail.type,entityId:tid,kind:v.kind,filename:file.name,mime:file.type,base64:await fileBase64(file)}}
    else if(kind==='device'){path='/devices';body={externalDeviceId:v.externalDeviceId,equipmentId:tid,staleAfterMinutes:Number(v.staleAfterMinutes)}}
    else if(kind==='password'){await api('/me/password','POST',v);formEl.reset();return message('Password changed')}
    await api(path,method,body);state.pad=null;await refresh(done);
  }catch(e){message(e.message,true)}
}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-download]');if(!a)return;e.preventDefault();try{const r=await fetch(a.href,{headers:{authorization:`Bearer ${state.token}`}});if(!r.ok)throw Error('Unable to download');const url=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=url;link.download=a.textContent;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){message(err.message,true)}});
render();
