const $=s=>document.querySelector(s),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={token:sessionStorage.getItem('mc_token'),user:JSON.parse(sessionStorage.getItem('mc_user')||'null'),tickets:[],selected:null,notice:'',error:'',online:navigator.onLine,pending:0};
if(state.user)state.tickets=JSON.parse(localStorage.getItem(`mc_tickets_${state.user.id}`)||'[]');
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('mouldcare-field',1);r.onupgradeneeded=()=>r.result.createObjectStore('actions',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function stored(mode,op){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('actions',mode),store=tx.objectStore('actions'),req=op(store);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
const queued=()=>stored('readonly',s=>s.getAll());
async function pending(){state.pending=(await queued()).filter(x=>x.userId===state.user?.id).length;render();}
async function request(path,method='GET',body,actionId){const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json',authorization:`Bearer ${state.token}`,...(actionId?{'x-client-action-id':actionId}:{})},body:body==null?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||`HTTP ${r.status}`),{http:true,status:r.status});return data;}
async function mutate(path,body){const item={id:crypto.randomUUID(),userId:state.user.id,path,body,createdAt:new Date().toISOString()};if(!navigator.onLine){await stored('readwrite',s=>s.put(item));state.notice='Saved on this device. It will sync when connected.';await pending();return}try{await request(path,'POST',body,item.id);state.notice='Saved and synced';await refresh();}catch(e){if(e.http){state.error=e.message;render();return}await stored('readwrite',s=>s.put(item));state.notice='Connection dropped. Saved on this device for retry.';await pending();}}
async function sync(){if(!navigator.onLine||!state.token||!state.user)return;const items=(await queued()).filter(x=>x.userId===state.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));for(const item of items){try{await request(item.path,'POST',item.body,item.id);await stored('readwrite',s=>s.delete(item.id));}catch(e){state.error=e.http?`Queued action needs review: ${e.message}`:'Still offline. Will retry later.';break}}await pending();await refresh();}
async function refresh(){if(!state.user)return;try{state.tickets=await request('/tickets');localStorage.setItem(`mc_tickets_${state.user.id}`,JSON.stringify(state.tickets));if(state.selected)state.selected=await request(`/tickets/${state.selected.id}`);state.online=true;}catch(e){state.online=false;state.error='Showing cached work. Changes will queue locally.'}render();}
function badge(s){return `<span class="badge ${safe(s)}">${safe(s?.replaceAll('_',' '))}</span>`}
function render(){if(!state.user){$('#app').innerHTML=`<div class="app"><div class="header"><div class="brand">Mould<span>Care</span> Field</div><div class="sub">Engineer mobile workspace</div></div><div class="login card"><h2>Sign in</h2><form id="login"><label>Email<input name="email" type="email" value="engineer@demo.test" required></label><label>Password<input name="password" type="password" value="DemoPass123!" required></label><button class="full">Sign in</button></form><p class="muted">Demo: engineer@demo.test, atlas@demo.test, euro@demo.test. Password: DemoPass123!</p>${state.error?`<div class="notice error">${safe(state.error)}</div>`:''}</div></div>`;$('#login').onsubmit=login;return}
  $('#app').innerHTML=`<div class="app"><div class="header"><div class="row"><div><div class="brand">Mould<span>Care</span> Field</div><div class="sub">${safe(state.user.name)} · ${safe(state.user.role.replaceAll('_',' '))}</div></div><div>${state.online?'Online':'<span class="offline">Offline</span>'} ${state.pending?`<span class="count">${state.pending} queued</span>`:''}</div></div></div><div class="content">${state.notice?`<div class="notice">${safe(state.notice)}</div>`:''}${state.error?`<div class="notice error">${safe(state.error)}</div>`:''}${state.selected?detail():list()}</div><div class="footer"><button class="secondary" id="back">${state.selected?'← Work list':'Sign out'}</button><button id="sync">Sync now</button></div></div>`;
  $('#back').onclick=()=>{if(state.selected){state.selected=null;state.notice='';state.error='';render()}else if(state.pending){state.error='Sync queued work before signing out.';render()}else{sessionStorage.removeItem('mc_token');sessionStorage.removeItem('mc_user');localStorage.removeItem(`mc_tickets_${state.user.id}`);state.token=null;state.user=null;state.tickets=[];render()}};
  $('#sync').onclick=sync;
  document.querySelectorAll('[data-ticket]').forEach(x=>x.onclick=async()=>{const id=x.dataset.ticket;state.selected=state.tickets.find(t=>t.id===id);render();try{state.selected=await request(`/tickets/${id}`);render()}catch{}});
  document.querySelectorAll('[data-form]').forEach(x=>x.onclick=()=>showForm(x.dataset.form));
  if($('#qr-lookup'))$('#qr-lookup').onsubmit=async e=>{e.preventDefault();const code=new FormData(e.target).get('qr').trim();try{const asset=await request(`/equipment/lookup?qr=${encodeURIComponent(code)}`);const ticket=state.tickets.find(t=>asset.ticketIds.includes(t.id));if(!ticket)throw Error('No assigned ticket for this equipment');state.selected=await request(`/tickets/${ticket.id}`);state.error='';render()}catch(err){state.error=err.message;render()}};
}
function list(){return `<div class="card"><form id="qr-lookup"><label>Equipment QR label<input name="qr" placeholder="MC:..." required></label><button class="full">Find assigned work</button></form></div><div class="section">Assigned work</div>${state.tickets.length?state.tickets.map(t=>`<div class="card" data-ticket="${safe(t.id)}"><div class="row"><h2>${safe(t.title)}</h2>${badge(t.priority)}</div><p class="muted">${safe(t.symptoms)}</p><div class="row"><span>${badge(t.status)}</span><span class="muted">${new Date(t.created_at).toLocaleDateString()}</span></div></div>`).join(''):'<div class="card empty">No assigned tickets</div>'}`}
function detail(){const t=state.selected,work=t.workLogs||[],check=t.checklist||[],events=t.events||[];return `<div class="actions"><button class="secondary" data-form="status">Update status</button><button data-form="work">Log work</button><button class="secondary" data-form="check">Checklist</button><button class="secondary" data-form="photo">Photo evidence</button></div><div id="form-slot"></div><div class="card"><div class="row"><h2>${safe(t.title)}</h2>${badge(t.priority)}</div><p>${badge(t.status)} · ${safe(t.error_codes||'No error code')}</p><p><b>Asset</b><br>${safe(t.asset?.make||'')} ${safe(t.asset?.model||'')} · ${safe(t.asset?.serial_number||'')}<br>${safe(t.plant?.name||'')} · ${safe(t.asset?.location||'')}</p><p><b>Symptoms</b><br>${safe(t.symptoms)}</p><p><b>Production impact</b><br>${safe(t.production_impact)}</p><p class="muted">Downtime: ${t.downtime_minutes} min</p></div><div class="section">Checklist</div><div class="card">${check.length?check.map(c=>`<p>${c.done?'☑':'☐'} ${safe(c.item)} <span class="muted">${safe(c.note)}</span></p>`).join(''):'No items yet'}</div><div class="section">Work log</div><div class="card">${work.length?work.map(w=>`<p>${safe(w.description)}<br><span class="muted">${w.minutes} min · ${safe(w.parts_used)}</span></p>`).join(''):'No work logged yet'}</div><div class="section">Activity</div><div class="card">${events.length?events.map(x=>`<p>${badge(x.event_type)}<br><span class="muted">${new Date(x.created_at).toLocaleString()} · ${safe(x.detail)}</span></p>`).join(''):'No updates yet'}</div>`}
function showForm(kind){const t=state.selected;let html='';if(kind==='status')html=`<label>Status<select name="status">${['accepted','in_progress','escalated','completed'].map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('')}</select></label><label>Downtime minutes<input name="downtimeMinutes" type="number" min="0" value="${t.downtime_minutes}"></label><label>Update note<textarea name="note"></textarea></label>`;if(kind==='work')html='<label>Work performed<textarea name="description" required></textarea></label><label>Minutes<input name="minutes" type="number" min="1" required></label><label>Parts used<input name="partsUsed"></label>';if(kind==='check')html='<label>Checklist item<input name="item" required></label><label>Note<input name="note"></label>';if(kind==='photo')html='<label>Photo evidence<input name="file" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required></label>';$('#form-slot').innerHTML=`<div class="card"><h2>${{status:'Update status',work:'Log work',check:'Add checklist item',photo:'Attach photo'}[kind]}</h2><form id="action-form">${html}<button class="full">Save</button></form></div>`;$('#action-form').onsubmit=e=>submit(e,kind)}
async function submit(e,kind){e.preventDefault();const f=new FormData(e.target),v=Object.fromEntries(f),t=state.selected;let path,body;if(kind==='status'){path=`/tickets/${t.id}/status`;body={status:v.status,note:v.note,downtimeMinutes:Number(v.downtimeMinutes)}}if(kind==='work'){path=`/tickets/${t.id}/work-logs`;body={description:v.description,minutes:Number(v.minutes),partsUsed:v.partsUsed}}if(kind==='check'){path=`/tickets/${t.id}/checklist`;body={item:v.item,note:v.note,done:false}}if(kind==='photo'){const file=f.get('file');if(file.size>5*1024*1024){state.error='Photo exceeds 5 MB';render();return}const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});path='/attachments';body={entityType:'ticket',entityId:t.id,kind:'evidence',filename:file.name,mime:file.type,base64}}$('#form-slot').innerHTML='';await mutate(path,body)}
async function login(e){e.preventDefault();const v=Object.fromEntries(new FormData(e.target));try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)}),data=await r.json();if(!r.ok)throw Error(data.error);state.token=data.token;state.user=data.user;sessionStorage.setItem('mc_token',data.token);sessionStorage.setItem('mc_user',JSON.stringify(data.user));state.error='';state.tickets=JSON.parse(localStorage.getItem(`mc_tickets_${state.user.id}`)||'[]');await pending();await refresh();await sync()}catch(err){state.error=err.message;render()}}
window.addEventListener('online',()=>{state.online=true;sync()});window.addEventListener('offline',()=>{state.online=false;render()});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/mobile/sw.js').catch(()=>{});
if(state.user){pending().then(refresh)}else render();
